#!/usr/bin/env node
// Cortex MCP stdio↔HTTP bridge — auto-generated by the hangarx-obsidian plugin.
// Do not edit; this file is rewritten on every MCP enable.
'use strict';

const http = require('http');
const url = require('url');
const readline = require('readline');

const targetUrl = process.env.CORTEX_MCP_URL;
const token = process.env.CORTEX_MCP_TOKEN;

if (!targetUrl || !token) {
  process.stderr.write('cortex-mcp-bridge: CORTEX_MCP_URL and CORTEX_MCP_TOKEN env vars are required\n');
  process.exit(1);
}

const parsed = url.parse(targetUrl);

function forward(line) {
  let request;
  try { request = JSON.parse(line); } catch (e) { return; }
  const isNotification = request.id === undefined || request.id === null;
  const data = Buffer.from(line, 'utf8');
  const opts = {
    hostname: parsed.hostname,
    port: parsed.port || 80,
    path: parsed.path || '/',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': data.length,
      'Authorization': 'Bearer ' + token,
    },
  };
  const req = http.request(opts, function (res) {
    let body = '';
    res.setEncoding('utf8');
    res.on('data', function (chunk) { body += chunk; });
    res.on('end', function () {
      if (isNotification) return;
      const trimmed = body.trim();
      if (trimmed) process.stdout.write(trimmed + '\n');
    });
  });
  req.on('error', function (err) {
    if (isNotification) return;
    process.stdout.write(JSON.stringify({
      jsonrpc: '2.0',
      id: request.id,
      error: { code: -32000, message: 'bridge: ' + err.message },
    }) + '\n');
  });
  req.write(data);
  req.end();
}

const rl = readline.createInterface({ input: process.stdin });
rl.on('line', forward);
rl.on('close', function () { process.exit(0); });
